spring:
  datasource:
    url: jdbc:mysql://13.124.242.194:3306/BeyondMeeting?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #show_sql: true
        format_sql: true

  logging.level:
    org.hibernate.SQL: info
    #org.hibernate.type: trace

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1054865786780-6c9h7c30tcd2icidolld1fius79trqvr.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080, http://13.124.242.194:3000, http://13.124.242.194:8080, https://13.124.242.194:8080, https://13.124.242.194:3000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    # 13.124.242.194
    authorizedRedirectUris:
      - https://i6c101.p.ssafy.io:3000/oauth2/redirect
      - https://i6c101.p.ssafy.io/oauth2/redirect
      - https://localhost/oauth2/redirect
      - https://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

#https 사용을 위한 추가 NamSoo 21.02.07
server:
  servlet:
    context-path: /api
  port: 8082
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/ssafy.p12
    key-store-password: ssafyssafy
    key-alias: ssafy
trust:
  store: classpath:keystore/ssafy.p12
  store.password: ssafyssafy